version: '3.9'

services:
  mongo:
    image: mongo:7.0.7-rc0-jammy
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: videoChatMongoUserName
      MONGO_INITDB_ROOT_PASSWORD: videoChatMongoPassword
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: videoChatMongoUserName
      ME_CONFIG_MONGODB_ADMINPASSWORD: videoChatMongoPassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://videoChatMongoUserName:videoChatMongoPassword@localhost:27017/
    depends_on:
      - mongo

volumes:
  mongo_data:
